package backend.classes;

import java.util.ArrayList;

public class HTMLProvider {

	public static String getIndex() {

		String s = "<!doctype html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n" + "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n" + "\r\n" + "\r\n"
				+ "  <title>Home-Saloon</title>\r\n"
				+ "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n"
				+ "    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n"
				+ "</head>\r\n" + "\r\n" + "<body>\r\n"
				+ "  <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n" + "    \r\n"
				+ "    <div class=\"container-fluid\">\r\n"
				+ "      <a class=\"navbar-brand\" href=\"#\">Saloon</a>\r\n"
				+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n"
				+ "        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n"
				+ "        <span class=\"navbar-toggler-icon\"></span>\r\n" + "      </button>\r\n"
				+ "      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n"
				+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n" + "          <li class=\"nav-item\">\r\n"
				+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"Entry\">Home</a>\r\n"
				+ "          </li>\r\n" + "         \r\n" + "          <li class=\"nav-item\">\r\n"
				+ "            <a class=\"nav-link\" href=\"#about\">About</a>\r\n" + "          </li>\r\n"
				+ "          <!-- <li class=\"nav-item dropdown\">\r\n"
				+ "            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n"
				+ "              Blog\r\n" + "            </a>\r\n" + "            <ul class=\"dropdown-menu\">\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n"
				+ "              <li><hr class=\"dropdown-divider\"></li>\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n"
				+ "            </ul>\r\n" + "          </li> -->\r\n" + "          <li class=\"nav-item dropdown\">\r\n"
				+ "            <a class=\"\" href=\"#\" role=\"\" data-bs-toggle=\"\" aria-expanded=\"\">\r\n"
				+ "             \r\n" + "            </a>\r\n" + "            <ul class=\"dropdown-menu\">\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n"
				+ "              <li><hr class=\"dropdown-divider\"></li>\r\n"
				+ "              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n"
				+ "            </ul>\r\n" + "          </li>\r\n" + "          <li class=\"nav-item\">\r\n"
				+ "            <a class=\"nav-link\" href=\"cart\">Cart</a>\r\n" + "          </li>\r\n" + "        </ul>\r\n"
				+ "        <form class=\"d-flex\" role=\"search\">\r\n" + "\r\n"
				+ "          <li><a class=\"btn btn-outline-success\" href=\"/style_up/sigup.html\" role=\"button\">signup</a></li>\r\n"
				+ "          <li></li><a class=\"btn btn-warning\" href=\"/style_up/login.html\" role=\"button\">Login</a></li>\r\n"
				+ "        </form>\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </nav>\r\n" + "\r\n"
				+ "  <div id=\"carouselExampleCaptions\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n"
				+ "\r\n" + "    <div class=\"carousel-indicators\">\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\"\r\n"
				+ "        aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\"\r\n"
				+ "        aria-label=\"Slide 2\"></button>\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\"\r\n"
				+ "        aria-label=\"Slide 3\"></button>\r\n" + "    </div>\r\n"
				+ "    <div class=\"carousel-inner\">\r\n" + "      <div class=\"carousel-item active\">\r\n"
				+ "        <img src=\"img/slide1.jpg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n" + "\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "          </form> -->\r\n" + "        </div>\r\n" + "      </div>\r\n"
				+ "      <div class=\"carousel-item\">\r\n"
				+ "        <img src=\"img/slide3.jpeg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "\r\n" + "          </form> -->\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "      <div class=\"carousel-item\">\r\n"
				+ "        <img src=\"img/slide2.jpeg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "          </form> -->\r\n" + "        </div>\r\n" + "      </div>\r\n"
				+ "    </div>\r\n"
				
				+ "    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n"
				+ "      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "      <span class=\"visually-hidden\">Previous</span>\r\n" + "    </button>\r\n"
				+ "    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n"
				+ "      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "      <span class=\"visually-hidden\">Next</span>\r\n" + "    </button>\r\n" + "  </div>\r\n"
//				+ "\r\n" + "  <div class=\"card\">\r\n" + "    <div class=\"card-header bg-info text-dark\">\r\n"
//				+ "      Quote\r\n" + "    </div>\r\n"
				+ "    <div class=\"card-body text-success  border border-warning \">\r\n"
				+ "      <blockquote class=\"blockquote mb-0\">\r\n"
				+ "         <p align=\"center\"> <i>~~Fashion is the Armour to Survive the reality of Everyday Life ~~</i></p>\r\n"
//				+ "        	
//				+ "<p align=\"center\"> <strong>BILL CUNNINGHAM</strong></p>\r\n"

				+ "      </blockquote>\r\n" + "    </div>\r\n" + "  </div>\r\n" + "\r\n" + "\r\n"
				+ "  <div class=\"row row-cols-1 row-cols-md-3 g-4 \">\r\n" + "    <div class=\"col  \">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/women.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n"
				+ "          <h5 class=\"card-title\">Women's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">Our committed and competent team is here to help keep your hair, nails, skin, and body healthy and beautiful. In addition to our regular beauty services such as pedicures, manicures, and hair services we will continue to perfect our skills and keep educated on all the latest styles. Enjoy our wide range of services in a cozy and luxurious environment. We look forward to serving you! \r\n"
				+ "            </p>\r\n" + "   "
				+ "    <p class=\"card-text\">400 INR </p>\n"
				+ "     </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "    <div class=\"col\">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/2.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n" + "          <h5 class=\"card-title\">Men's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">The art of looking handsome and getting makeovers has its own story for men and one cannot imagine the number of styles and treatments that can be done on these hunks. Moreover, the desire to have a unique identity is everyone's' want and Looks Salon makes that possible. From grooming to beauty sessions, we offer a wide range of services and treatments that every man wishes to get. </p>\r\n"
				+ "    <p class=\"card-text\">400 INR </p>\n"
				+ "        </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p2\" role=\"button\">Book</a>\r\n"
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "    <div class=\"col\">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/baby.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n" + "          <h5 class=\"card-title\">Kid's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">A kids haircut at Starfish is different from getting one at any other salon! With a cheerful set up and entertainment screens to the trained and child friendly team, it will be a special experience for your child! Kids love to walk out after a great haircut and a treat at the end of every visit.\r\n"
				+ "            </p>\r\n"
				+ "    <p class=\"card-text\">400 INR </p>\n"
				+ "        </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p3\" role=\"button\">Book</a>\r\n"
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "  </div>\r\n"
				+ "  <!--------------------------------------Order-Now-------------------------------------------->\r\n"
				+ "  <div class=\"container col-xxl-8 px-4 py-5\" id=\"order\">\r\n"
				+ "    <div class=\"row flex-lg-row-reverse align-items-center g-5 py-5\">\r\n"
				+ "      <div class=\"col-10 col-sm-8 col-lg-6\" data-aos=\"fade-out-down\">\r\n"
				+ "        <img src=\"img/theme1.jpg\" class=\"d-block mx-lg-auto img-fluid\" alt=\"Bootstrap Themes\" width=\"800\" height=\"800\"\r\n"
				+ "          loading=\"lazy\">\r\n" + "      </div>\r\n"
				+ "      <div class=\"col-lg-6\" data-aos=\"fade-out-up\">\r\n"
				+ "        <h1 class=\"display-5 fw-bold lh-1 mb-3\">Book your<b style=\"color:rgb(245, 0, 0) ;\"><i>\"appointment\r\n"
				+ "              \"</i></b>Now...</h1>\r\n"
//				+ "        <p class=\"lead\">Hey Guys, Get your <i>Online appointment</i> Favorites barbor right to your doorstep with\r\n"
//				+ "          <i>Online\r\n"
//				+ "            Foods</i>. we are here to provide you Halal and fresh food.\r\n"
//				+ "          We use only the best ingredients to cook delicious meals for you. In our menu you will find a wide variety of\r\n"
//				+ "          dishes, deserts and drinks. Why are you waiting, order now.</p>\r\n"
				+ "        <!-- <div class=\"d-grid gap-2 d-md-flex justify-content-md-start\">\r\n"
				+ "        <a href=\"orders.html\"> <button type=\"button\" class=\"btn btn-danger btn-lg px-4 me-md-4\">Order Now</button>\r\n"
				+ "        </a>\r\n" + "      </div> -->\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </div>\r\n"
				+ "\r\n" + "\r\n" + "  <section class=\"py-5\" id=\"about\">\r\n"
				+ "    <div class=\"container-fluid\">\r\n" + "      <div class=\"row\">\r\n"
				+ "        <div class=\"col-lg-5 col-6 mx-lg-0 mx-auto px-lg-5 px-md-0 my-auto\" data-aos=\"fade-in-down\"\r\n"
				+ "          data-aos-delay=\"300\">\r\n"
				+ "          <img class=\"w-100 border-radius-lg shadow\" src=\"img/themes2.jpg\" style=\"width: 600px;height: 400px; ;\">\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-lg-4 col-10 d-flex justify-content-center flex-column mx-auto text-lg-start text-center\"\r\n"
				+ "          data-aos=\"fade-out-down\" data-aos-delay=\"200\">\r\n"
				+ "          <h2 class=\"mb-0 mt-lg-0 mt-4 text-gradient text-danger\">About us</h2>\r\n"
//				+ "          <h2 class=\"mb-4\">And find some great partners</h2>\r\n"
//				+ "          <p class=\"lead\">It really matters and then like it really doesn’t matter. What matters is the people who are\r\n"
//				+ "            sparked by it. And the people who are like offended by it, it doesn’t matter. </p>\r\n"
				+ "          <ul class=\"m-lg-2 m-auto text-danger\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
				+ "            <li class=\"lead mb-2 \" >Saurav Mukherjee <p>Roll No. 011 </p></li>\r\n"

				+ "            <li class=\"lead mb-2\">Priyanka Sahu <p>Roll No. 056</p></li>\r\n"
				+ "            <li class=\"lead mb-2\">Rammohan Chaudhry <p>Roll No. 052 </p></li>\r\n"
				+ "            <li class=\"lead mb-2\">Souvik Mondal<p>Roll No. 078 </p></li>\r\n"

				
				+ "          </ul>\r\n"
//				+ "          <p class=\"blockquote my-3 ps-2\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
//				+ "            <span class=\"text-bold\">“Lorem itur at isibusdam, ratione minus doloremque!.”</span>\r\n"
//				+ "            <br>\r\n"
//				+ "            <small class=\"blockquote-footer\" data-aos=\"fade-in-bottom\" data-aos-delay=\"100\">\r\n"
//				+ "              Ashok kumar\r\n"
//				+ "            </small>\r\n"
//				+ "          </p>\r\n"
				+ "        </div>\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </section>\r\n" + "\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js\"\r\n"
				+ "    integrity=\"sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js\"\r\n"
				+ "    integrity=\"sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n" + "\r\n" + "  <!--AOS-->\r\n"
				+ "  <script src=\"https://unpkg.com/aos@next/dist/aos.js\"></script>\r\n" + "  <script>\r\n"
				+ "    AOS.init();\r\n" + "  </script>\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n"
				+ "    integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n" + "</body>\r\n" + "\r\n" + "</html>";
		return s;
	}

	// when loggeg in
	public static String getIndex(String name) {

		String s = "<!doctype html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n" + "<head>\r\n"
				+ "  <meta charset=\"utf-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n" + "\r\n" + "\r\n"
				+ "  <title>Home-Saloon</title>\r\n"
				+ "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n"
				+ "    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n"
				+ "</head>\r\n" + "\r\n" + "<body>\r\n"
+" <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
+ "    \n"
+ "    <div class=\"container-fluid\">\n"
+ "      <a class=\"navbar-brand\" href=\"#\">Saloon</a>\n"
+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n"
+ "        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
+ "        <span class=\"navbar-toggler-icon\"></span>\n"
+ "      </button>\n"
+ "      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
+ "          <li class=\"nav-item\">\n"
+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"Entry\">Home</a>\n"
+ "          </li>\n"
+ "         \n"
+ "          <li class=\"nav-item\">\n"
+ "            <a class=\"nav-link\" href=\"#about\">About</a>\n"
+ "          </li>\n"
+ "          <!-- <li class=\"nav-item dropdown\">\n"
+ "            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n"
+ "              Dropdown\n"
+ "            </a>\n"
+ "            <ul class=\"dropdown-menu\">\n"
+ "              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n"
+ "              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n"
+ "              <li><hr class=\"dropdown-divider\"></li>\n"
+ "              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n"
+ "            </ul>\n"
+ "          </li> -->\n"
+ "          <li class=\"\">\n"
+ "            <a class=\"\" href=\"#\" >\n"
+ "          \n"
+ "            </a>\n"
+ "          \n"
+ "          </li>\n"
+ "          <li class=\"nav-item\">\n"
+ "            <a class=\"nav-link\" href=\"cart\">Cart</a>\n"
+ "          </li>\n"
+ "        </ul>\n"
+ "        <form class=\"d-flex\" role=\"search\">"
				+ "          <li><a class=\"btn btn-outline-success\" >Welcome " + name + "</a></li>\r\n"
				+ "          <li></li><a class=\"btn btn-warning\" href=\"logout\" role=\"button\">Log Out</a></li>\r\n"
				+ "        </form>\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </nav>\r\n" + "\r\n"
				+ "  <div id=\"carouselExampleCaptions\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n"
				+ "\r\n" + "    <div class=\"carousel-indicators\">\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\"\r\n"
				+ "        aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\"\r\n"
				+ "        aria-label=\"Slide 2\"></button>\r\n"
				+ "      <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\"\r\n"
				+ "        aria-label=\"Slide 3\"></button>\r\n" + "    </div>\r\n"
				+ "    <div class=\"carousel-inner\">\r\n" + "      <div class=\"carousel-item active\">\r\n"
				+ "        <img src=\"img/slide1.jpg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n" + "\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "          </form> -->\r\n" + "        </div>\r\n" + "      </div>\r\n"
				+ "      <div class=\"carousel-item\">\r\n"
				+ "        <img src=\"img/slide3.jpeg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "\r\n" + "          </form> -->\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "      <div class=\"carousel-item\">\r\n"
				+ "        <img src=\"img/slide2.jpeg\" class=\"d-block w-100\" alt=\"...\" style=\"width: 300px; height: 300px;\">\r\n"
				+ "        <div class=\"carousel-caption d-none d-md-block\">\r\n"
				+ "          <!-- <h2>welcome to Saloon</h2>\r\n"
				+ "          <p>Some representative placeholder content for the first slide.</p> -->\r\n"
				+ "          <!-- <form class=\"d-flex\" role=\"search\">\r\n"
				+ "            <div class=\"d-grid gap-2 col-2 mx-auto\">\r\n"
				+ "              <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
				+ "            </div>\r\n" + "          </form> -->\r\n" + "        </div>\r\n" + "      </div>\r\n"
				+ "    </div>\r\n"
				+ "    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n"
				+ "      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "      <span class=\"visually-hidden\">Previous</span>\r\n" + "    </button>\r\n"
				+ "    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n"
				+ "      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n"
				+ "      <span class=\"visually-hidden\">Next</span>\r\n" + "    </button>\r\n" + "  </div>\r\n"
//				+ "\r\n" + "  <div class=\"card\">\r\n" + "    <div class=\"card-header bg-info text-dark\">\r\n"
//				+ "      Quote\r\n" + "    </div>\r\n"
				+ "    <div class=\"card-body text-danger  border border-warning \">\r\n"
				+ "      <blockquote class=\"blockquote mb-0\">\r\n"
				+ "         <p align=\"center\"> <i>~~Fashion is the Armour to Survive the reality of Everyday Life ~~</i></p>\r\n"
//				+ "        	
//				+ "<p align=\"center\"> <strong>BILL CUNNINGHAM</strong></p>\r\n"

				+ "      </blockquote>\r\n" + "    </div>\r\n" + "  </div>\r\n" + "\r\n" + "\r\n"
				+ "  <div class=\"row row-cols-1 row-cols-md-3 g-4 \">\r\n" + "    <div class=\"col  \">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/women.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n"
				+ "          <h5 class=\"card-title\">Women's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">Our committed and competent team is here to help keep your hair, nails, skin, and body healthy and beautiful. In addition to our regular beauty services such as pedicures, manicures, and hair services we will continue to perfect our skills and keep educated on all the latest styles. Enjoy our wide range of services in a cozy and luxurious environment. We look forward to serving you! \r\n"
				+ "            </p>\r\n"
				+ "    <p class=\"card-text\">400 INR </p>\n"+ "        </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p1\" role=\"button\">Book</a>\r\n"
			
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "    <div class=\"col\">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/2.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n" + "          <h5 class=\"card-title\">Men's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">The art of looking handsome and getting makeovers has its own story for men and one cannot imagine the number of styles and treatments that can be done on these hunks. Moreover, the desire to have a unique identity is everyone's' want and Looks Salon makes that possible. From grooming to beauty sessions, we offer a wide range of services and treatments that every man wishes to get. </p>\r\n"
				+ "    <p class=\"card-text\">400 INR </p>\n"
				+ "        </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p2\" role=\"button\">Book</a>\r\n"
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "    <div class=\"col\">\r\n"
				+ "      <div class=\"card h-100 border border-warning\">\r\n"
				+ "        <img src=\"img/baby.jpg\" class=\"card-img-top\" alt=\"...\" style=\"width: 489px;height: 400px;\">\r\n"
				+ "        <div class=\"card-body\">\r\n" + "          <h5 class=\"card-title\">Kid's Parlour</h5>\r\n"
				+ "          <p class=\"card-text\">A kids haircut at Starfish is different from getting one at any other salon! With a cheerful set up and entertainment screens to the trained and child friendly team, it will be a special experience for your child! Kids love to walk out after a great haircut and a treat at the end of every visit.\r\n"
				+ "            </p>\r\n" 
				+ "    <p class=\"card-text\">400 INR </p>\n"
				+ "        </div>\r\n" + "        <form class=\"d-flex\" role=\"search\">\r\n"
				+ "          <div class=\"d-grid gap-2 col-2 mx-lg-0\">\r\n"
				+ "            <a class=\"btn btn-danger\" href=\"ordersManager?pid=p3\" role=\"button\">Book</a>\r\n"
				+ "          </div>\r\n" + "\r\n" + "        </form>\r\n"
				+ "        <div class=\"card-footer border border-success\">\r\n"
				+ "          <small class=\"text-muted\">Last updated 3 mins ago</small>\r\n" + "        </div>\r\n"
				+ "      </div>\r\n" + "    </div>\r\n" + "  </div>\r\n"
				+ "  <!--------------------------------------Order-Now-------------------------------------------->\r\n"
				+ "  <div class=\"container col-xxl-8 px-4 py-5\" id=\"order\">\r\n"
				+ "    <div class=\"row flex-lg-row-reverse align-items-center g-5 py-5\">\r\n"
				+ "      <div class=\"col-10 col-sm-8 col-lg-6\" data-aos=\"fade-out-down\">\r\n"
				+ "        <img src=\"img/theme1.jpg\" class=\"d-block mx-lg-auto img-fluid\" alt=\"Bootstrap Themes\" width=\"800\" height=\"800\"\r\n"
				+ "          loading=\"lazy\">\r\n" + "      </div>\r\n"
				+ "      <div class=\"col-lg-6\" data-aos=\"fade-out-up\">\r\n"
				+ "        <h1 class=\"display-5 fw-bold lh-1 mb-3\">Book your<b style=\"color:rgb(245, 0, 0) ;\"><i>\"appointment\r\n"
				+ "              \"</i></b>Now...</h1>\r\n"
//				+ "        <p class=\"lead\">Hey Guys, Get your <i>Online appointment</i> Favorites barbor right to your doorstep with\r\n"
//				+ "          <i>Online\r\n"
//				+ "            Foods</i>. we are here to provide you Halal and fresh food.\r\n"
//				+ "          We use only the best ingredients to cook delicious meals for you. In our menu you will find a wide variety of\r\n"
//				+ "          dishes, deserts and drinks. Why are you waiting, order now.</p>\r\n"
				+ "        <!-- <div class=\"d-grid gap-2 d-md-flex justify-content-md-start\">\r\n"
				+ "        <a href=\"orders.html\"> <button type=\"button\" class=\"btn btn-danger btn-lg px-4 me-md-4\">Order Now</button>\r\n"
				+ "        </a>\r\n" + "      </div> -->\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </div>\r\n"
				+ "\r\n" + "\r\n" + "  <section class=\"py-5\" id=\"about\">\r\n"
				+ "    <div class=\"container-fluid\">\r\n" + "      <div class=\"row\">\r\n"
				+ "        <div class=\"col-lg-5 col-6 mx-lg-0 mx-auto px-lg-5 px-md-0 my-auto\" data-aos=\"fade-in-down\"\r\n"
				+ "          data-aos-delay=\"300\">\r\n"
				+ "          <img class=\"w-100 border-radius-lg shadow\" src=\"img/themes2.jpg\" style=\"width: 600px;height: 400px; ;\">\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"col-lg-4 col-10 d-flex justify-content-center flex-column mx-auto text-lg-start text-center\"\r\n"
				+ "          data-aos=\"fade-out-down\" data-aos-delay=\"200\">\r\n"
				+ "          <h2 class=\"mb-0 mt-lg-0 mt-4 text-gradient text-danger\">About us</h2>\r\n"
//				+ "          <h2 class=\"mb-4\">And find some great partners</h2>\r\n"
//				+ "          <p class=\"lead\">It really matters and then like it really doesn’t matter. What matters is the people who are\r\n"
//				+ "            sparked by it. And the people who are like offended by it, it doesn’t matter. </p>\r\n"
				+ "          <ul class=\"m-lg-2 m-auto text-danger\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
				+ "            <li class=\"lead mb-2 \" >Saurav Mukherjee <p>Roll No. 011 </p></li>\r\n"

				+ "            <li class=\"lead mb-2\">Priyanka Sahu <p>Roll No. 056</p></li>\r\n"
				+ "            <li class=\"lead mb-2\">RammohanChaudhry <p>Roll No. 052 </p></li>\r\n"
				+ "            <li class=\"lead mb-2\">Souvik Mondal <p>Roll No. 078 </p></li>\r\n"

		
				+ "          </ul>\r\n"
//				+ "          <p class=\"blockquote my-3 ps-2\" data-aos=\"fade-in-down\" data-aos-delay=\"300\">\r\n"
//				+ "            <span class=\"text-bold\">“Lorem itur at isibusdam, ratione minus doloremque!.”</span>\r\n"
//				+ "            <br>\r\n"
//				+ "            <small class=\"blockquote-footer\" data-aos=\"fade-in-bottom\" data-aos-delay=\"100\">\r\n"
//				+ "              Ashok kumar\r\n"
//				+ "            </small>\r\n"
//				+ "          </p>\r\n"
				+ "        </div>\r\n" + "      </div>\r\n" + "    </div>\r\n" + "  </section>\r\n" + "\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js\"\r\n"
				+ "    integrity=\"sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js\"\r\n"
				+ "    integrity=\"sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n" + "\r\n" + "  <!--AOS-->\r\n"
				+ "  <script src=\"https://unpkg.com/aos@next/dist/aos.js\"></script>\r\n" + "  <script>\r\n"
				+ "    AOS.init();\r\n" + "  </script>\r\n"
				+ "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\r\n"
				+ "    integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\"\r\n"
				+ "    crossorigin=\"anonymous\"></script>\r\n" + "</body>\r\n" + "\r\n" + "</html>";
		return s;
	}

	public static String getCart(String name, ArrayList<BookedItem> bookedProducts) {
		
		String s="";
		  s="<!doctype html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n" + "<head>\r\n"
					+ "  <meta charset=\"utf-8\">\r\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n" + "\r\n" + "\r\n"
					+ "  <title>Cart-Saloon</title>\r\n"
					+ "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n"
					+ "    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n"
					+ "</head>\r\n" + "\r\n" + "<body>\r\n"
	+" <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
	+ "    \n"
	+ "    <div class=\"container-fluid\">\n"
	+ "      <a class=\"navbar-brand\" href=\"#\">Saloon</a>\n"
	+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n"
	+ "        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
	+ "        <span class=\"navbar-toggler-icon\"></span>\n"
	+ "      </button>\n"
	+ "      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
	+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"Entry\">Home</a>\n"
	+ "          </li>\n"
	+ "         \n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link\" href=\"Entry#about\">About</a>\n"
	+ "          </li>\n"
	+ "          <!-- <li class=\"nav-item dropdown\">\n"
	+ "            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n"
	+ "              Dropdown\n"
	+ "            </a>\n"
	+ "            <ul class=\"dropdown-menu\">\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n"
	+ "              <li><hr class=\"dropdown-divider\"></li>\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n"
	+ "            </ul>\n"
	+ "          </li> -->\n"
	+ "          <li class=\"\">\n"
	+ "            <a class=\"\" href=\"#\" >\n"
	+ "          \n"
	+ "            </a>\n"
	+ "          \n"
	+ "          </li>\n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link\" href=\"cart\">Cart</a>\n"
	+ "          </li>\n"
	+ "        </ul>\n"
	+ "        <form class=\"d-flex\" role=\"search\">"
					+ "          <li><a class=\"btn btn-outline-success\" >Welcome " + name + "</a></li>\r\n"
					+ "          <li></li><a class=\"btn btn-warning\" href=\"/style_up/logout\" role=\"button\">Log Out</a></li>\r\n"
					+ "        </form>\r\n   </div>\n"
					+ "    </div>\n"
					+ "  </nav>\n"
					+ "  "  ;
		  String item="";
		  
		 
		  
		  for(int i=0;i<bookedProducts.size();i++)
			  
		  {
		 item+= getBookedItems(bookedProducts.get(i));
                  
		  }
		  
		  if(item.length()==0) {
			  
			item= getEmptyCardBody("Your cart is Empty", "Entry");
			  
		  }
		  
		  String page=s+item;
		  
		  
		    
		
		
		return page;
	}

	

	public static String getCart() {
		
		String s="";
		  s="<!doctype html>\r\n" + "<html lang=\"en\">\r\n" + "\r\n" + "<head>\r\n"
					+ "  <meta charset=\"utf-8\">\r\n"
					+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n" + "\r\n" + "\r\n"
					+ "  <title>Cart-Saloon</title>\r\n"
					+ "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n"
					+ "    integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n"
					+ "</head>\r\n" + "\r\n" + "<body>\r\n"
	+" <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n"
	+ "    \n"
	+ "    <div class=\"container-fluid\">\n"
	+ "      <a class=\"navbar-brand\" href=\"#\">Saloon</a>\n"
	+ "      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n"
	+ "        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
	+ "        <span class=\"navbar-toggler-icon\"></span>\n"
	+ "      </button>\n"
	+ "      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n"
	+ "        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link active\" aria-current=\"page\" href=\"Entry\">Home</a>\n"
	+ "          </li>\n"
	+ "         \n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link\" href=\"Entry#about\">About</a>\n"
	+ "          </li>\n"
	+ "          <!-- <li class=\"nav-item dropdown\">\n"
	+ "            <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n"
	+ "              Dropdown\n"
	+ "            </a>\n"
	+ "            <ul class=\"dropdown-menu\">\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n"
	+ "              <li><hr class=\"dropdown-divider\"></li>\n"
	+ "              <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n"
	+ "            </ul>\n"
	+ "          </li> -->\n"
	+ "          <li class=\"\">\n"
	+ "            <a class=\"\" href=\"#\" >\n"
	+ "          \n"
	+ "            </a>\n"
	+ "          \n"
	+ "          </li>\n"
	+ "          <li class=\"nav-item\">\n"
	+ "            <a class=\"nav-link\" href=\"cart\">Cart</a>\n"
	+ "          </li>\n"
	+ "        </ul>\n"
	+ "        <form class=\"d-flex\" role=\"search\">"
	+ "          <li><a class=\"btn btn-outline-success\" href=\"/style_up/sigup.html\" role=\"button\">signup</a></li>\r\n"
	+ "          <li></li><a class=\"btn btn-warning\" href=\"/style_up/login.html\" role=\"button\">Login</a></li>\r\n"

					
	
					+ "        </form>\r\n   </div>\n"
					+ "    </div>\n"
					+ "  </nav>\n"
					+ "  "  ;
		  
		return s+getEmptyCardBody("Please Login First", "login.html");

	}
	
	private static String getBookedItems(BookedItem i) {
		ArrayList<String> productDtl= ProductDetails.getProductDetails(i.pid);
		
		String item=" <!-- items -->\n"
		 		+ "  \n"
		 		+ "  <div class=\"card mb-3\" style=\"width: 1150px;\">\n"
		 		+ "  <div class=\"row g-0\">\n"
		 		+ "    <div class=\"col-md-4\">\n"
		 		+ "      <img src=\""+ productDtl.get(2) +"\" class=\"img-fluid rounded-start\" style=\"width: 400px;height:350px;margin-top:10px;\" >\n"
		 		+ "    </div>\n"
		 		+ "    <div class=\"col-md-8\">\n"
		 		+ "    \n"
		 		+ " <!-- inner div opens -->\n"
		 		+ " \n"
		 		+ "  <div class=\"card text-bg-secondary mb-3\" style=\"width: 700px;height:350px; margin-left:50px;margin-top:10px;\">\n"
		 		+ "  <div class=\"card-header\">Booked</div>\n"
		 		+ "  <div class=\"card-body\">\n"
		 		+ "    <h5 class=\"card-title\">"+ productDtl.get(0)  +"</h5>\n"
		 		+ "    <p class=\"card-text\">"+ productDtl.get(1) +"</p>\n"
		 		+ "    <p class=\"card-text\">"+ "Date: "+i.date +"</p>\n"
		 		+ "    <p class=\"card-text\">"+"Address: "+i.address +"</p>\n"
		 		+ "    \n"
		 		+ "    <p class=\"card_prince\">400 INR</p>\n"
		 		+ "  </div>\n"
		 		+ "</div>\n"
		 		+ " <!-- inner div end -->\n"
		 		+ "    </div>\n"
		 		+ "  </div>\n"
		 		+ "</div>\n";
		 		
		
		return item;
	}
	
	
	private static String getEmptyCardBody(String text,String url) {
		String body = "<section class=\"hight:100px\" style=\"background-color: #9A616D; height:\">\n"
				+ "  <div class=\"container py-5 h-100\">\n"
				+ "    <div class=\"row d-flex justify-content-center align-items-center h-100\">\n"
				+ "      <div class=\"col col-xl-10\">\n"
				+ "        <div class=\"card\" style=\"border-radius: 1rem;\">\n"
				+ "          <div class=\"row g-0\">\n"
				+ "            <div class=\"col-md-6 col-lg-5 d-none d-md-block\">\n"
				+ "              <img src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp\"\n"
				+ "                alt=\"login form\" class=\"img-fluid\" style=\"border-radius: 1rem 0 0 1rem;\" />\n"
				+ "            </div>\n"
				+ "            <div class=\"col-md-6 col-lg-7 d-flex align-items-center\" style=\"background-color: #F19987\" >\n"
				+ "              <div class=\"card-body p-4 p-lg-5 text-black\">\n"
				+ "\n"
				+ "                <form >\n"
				+ "\n"
				+ "                  <div class=\"d-flex align-items-center mb-3 pb-1\">\n"
				+ "                    <i class=\"fas fa-cubes fa-2x me-3\" style=\"color: #ff6219;\"></i>\n"
				+ "                    \n"
				+ "                    <span><a class=\"nav-link h1 fw-bold mb-0\" href=\""+url+"\" style=\"font-size:5vw\"\" >"+text+"</a> </span>\n"
				+ "                  \n"
				+ "                  </div>\n"
				+ "\n"
				+ "\n"
				+ "                 \n"
				+ "                </form>\n"
				+ "\n"
				+ "              </div>\n"
				+ "            </div>\n"
				+ "          </div>\n"
				+ "        </div>\n"
				+ "      </div>\n"
				+ "    </div>\n"
				+ "  </div>\n"
				+ "</section>";
				
				
	return body;
		
		
	}
	
	
	
	public static String getBookingPage(String name, String mobile,String orderName) {
		String page= "<!doctype html>\n"
				+ "<html lang=\"en\">\n"
				+ "\n"
				+ "<head>\n"
				+ "  <!-- Required meta tags -->\n"
				+ "  <meta charset=\"utf-8\">\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
				+ "  <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n"
				+ "  <link rel=\"stylesheet\" href=\"assets/css/datepicker.css\">\n"
				+ "  <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n"
				+ "</head>\n"
				+ "\n"
				+ "<body>\n"
				+ "  <div class=\"inner-layer\">\n"
				+ "    <div class=\"container\">\n"
				+ "      <div class=\"row no-margin\">\n"
				+ "        <div class=\"col-sm-7\">\n"
				+ "          <div class=\"content\">\n"
				+ "            <h1>Book You Slot Now and Save your time</h1>\n"
				+ "            \n"
				+ "          </div>\n"
				+ "        </div>\n"
				+ "        <div class=\"col-sm-5\">\n"
				+ "          <div class=\"form-data\">\n"
				+ "            <div class=\"form-head\">\n"
				+ "              <h2>Book Appointment</h2>\n"
				+ "            </div>\n"
				+ "            <form action=\"confirmOrder\" method=\"get\" >\n"
				+ "            <div class=\"form-body border-warning\">\n"
				+ "              <div class=\"row form-row\">\n"
				+ "                <p class=\"form-control\">"+orderName+" </p>\n"
				+ "              </div>\n"
				
				+ "              <div class=\"row form-row\">\n"
				+ "                <p class=\"form-control\">"+name+" </p>\n"
				+ "              </div>\n"
				+ "              <div class=\"row form-row\">\n"
				+ "                <p  class=\"form-control\">"+mobile+"</p>\n"
				+ "              </div>\n"
				+ "              <div class=\"row form-row\">\n"
				+ "                <input id=\"dat\" type=\"text\" name =\"date\" placeholder=\"Appointment Date\" class=\"form-control\">\n"
				+ "              </div>\n"
				+ "\n"
				+ "              <h6>Address Details</h6>\n"
				+ "\n"
				+ "              <div class=\"row form-row\">\n"
				+ "              \n"
				+ "                  <input type=\"text\" name =\"address\" placeholder=\"Enter Address\" class=\"form-control\">\n"
				+ "                </div>\n"
				+ "                \n"
				+ "\n"
				+ "              <div class=\"row form-row\">\n"
				+ "                <button class=\"btn btn-success btn-appointment\">\n"
				+ "                  Book Appointment\n"
				+ "                </button>\n"
				+ "\n"
				+ "              </div>\n"
				+ "\n"
				+ "            </div>\n"
				+ "            </form>\n"
				+ "          </div>\n"
				+ "        </div>\n"
				+ "      </div>\n"
				+ "    </div>\n"
				+ "  </div>\n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "  <!-- Optional JavaScript -->\n"
				+ "  <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n"
				+ "  <script src=\"assets/js/jquery-3.3.1.min.js\"></script>\n"
				+ "  <script src=\"assets/js/popper.min.js\"></script>\n"
				+ "  <script src=\"assets/js/bootstrap.min.js\"></script>\n"
				+ "  <script src=\"assets/js/bootstrap-datepicker.js\"></script>\n"
				+ "\n"
				+ "  <script>\n"
				+ "    $(document).ready(function () {\n"
				+ "      $(\"#dat\").datepicker();\n"
				+ "    })\n"
				+ "  </script>\n"
				+ "\n"
				+ "</body>\n"
				+ "\n"
				+ "</html>";
		
		
		
		return page;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
